server:
  port: 0
spring:
  cloud:
    stream:
      instance-index: 0
      instance-count: 2
      bindings:
        input:          
          destination: topic.processor 
          content-type: application/json
          group: sink
          consumer:
            partitioned: true    
