server:
  port: 0
management:
  health:
    binders:
      enabled: true   
spring:
  cloud:
    stream:
      instance-index: 0
      instance-count: 2
      bindings:
        input:          
          destination: topic.processor 
          group: sink
          consumer:
            partitioned: true