server:
  port: 0
management:
  health:
    binders:
      enabled: true 
spring:
  cloud:
    stream:
      bindings:
        input:
          group: processor
          destination: topic.hashtagprocessor 
        output:
          destination: topic.processor
          producer:
            partitionKeyExtractorClass: com.springclouddemo.processor.service.EventPartitionExtractor
            partitionSelectorClass: com.springclouddemo.processor.service.EventPartitionExtractor
            partitionCount: 2
partition:
  candidates:
    - clinton
    - trump            
          
