server:
  port: 0
management:
  health:
    binders:
      enabled: true 
spring:
  cloud:
    stream:
      bindings:
        input:
          group: hashtagprocessor
          destination: topic.source 
        output:
          destination: topic.hashtagprocessor
